### PR TITLE
added soup recipe to resolve #3

### LINKED ISSUE #3: Soup
This repo is lacking a recipe for soup.

### PR DESCRIPTION
**Pull request by terne**
Resolves #3

### CODE REVIEW

**Comment by helenewegener1** [comment]
Can you please explain what you added?

**Comment by terne** [comment]
I added an onion soup recipe :)

**Comment by helenewegener1** [comment]
Ah okay! Can you please add salt to the soup? I think this will really make it perfect! When you fixed please commit and push again.

**Comment by helenewegener1** [comment]
Yummy yummy, salt in my tummy! 
Thank you for solving your own issues - this is a great life lesson!

**Pull request merged**
