### PR TITLE
added chocolate chip cookie recipe

### PR DESCRIPTION
**Pull request by wessel-mulder**
Resolves issue #5

### CODE REVIEW

**Comment by helenewegener1** [comment]
Great ! I think we need salt though! Please add this to the recipe and commit + push again

**Comment by wessel-mulder** [comment]
yes chef

**Comment by helenewegener1** [comment]
Yummy yummy - salt in my tummy! 
Thank you for solving your own issues - this is a great life lesson!

**Comment by wessel-mulder** [comment]
resolves #5

**Pull request merged**
